{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "orghub.name" . }}-postgres
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "orghub.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.postgres.storageClass }}
  storageClassName: {{ .Values.postgres.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.postgres.storageSize }}
{{- end }}
