apiVersion: v1
kind: Service
metadata:
  name: {{ include "orghub.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "orghub.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: orghub
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: app
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
